# Generated by Django 5.2.4 on 2025-07-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
